title: Programming Languages Reading Group
description: Augusta University Programming Languages Reading Group
markdown: kramdown
baseurl: "/plgroup"
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "past_semesters"
    values:
      layout: "semester"
  - scope:
      path: ""
    values:
      layout: "current"

collections:
  past_semesters:
    output: true
    permalink: /:path

exclude:
  - Gemfile
  - /*/papers.md
  - /*/awards.md
  - papers.md
  - awards.md