title: PL Reading Group
description: Augusta University Programming Languages Reading Group
markdown: kramdown
remote_theme: the-au-forml-lab/the-au-forml-lab.github.io
baseurl: "/plgroup"

defaults:
  - scope:
      path: ""
      type: "past_semesters"
    values:
      layout: "semester"
  - scope:
      path: ""
    values:
      layout: "current"

collections:
  past_semesters:
    output: true

exclude:
  - next.md
  - papers.md
  - Gemfile
  - readme.md