title: PL Reading Group
description: Augusta University Programming Languages Reading Group
markdown: kramdown
remote_theme: the-au-forml-lab/the-au-forml-lab.github.io
baseurl: "/plgroup"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "past_semesters"
    values:
      layout: "semester"
  - scope:
      path: ""
    values:
      layout: "current"

collections:
  past_semesters:
    output: true
    permalink: /:path

exclude:
  - Gemfile
  - /*/papers.md
  - /*/awards.md
  - next.md
  - papers.md
  - awards.md
  - readme.md