title: PL Reading Group
description: >- 
  PL Reading Group
markdown: kramdown
remote_theme: the-au-forml-lab/the-au-forml-lab.github.io
# fix the menu links
url: https://the-au-forml-lab.github.io
baseurl: ''