name: Choose paper

on:
  schedule:
            # ┌─────────── minute (0 - 59)
            # │  ┌────────── hour (0 - 23)
            # │  │ ┌────────── day of the month (1 - 31)
            # │  │ │ ┌────────── month (1 - 12 or JAN-DEC)
            # │  │ │ │ ┌────────── day of the week (0 - 6 or SUN-SAT)
            # │  │ │ │ │
            # │  │ │ │ │
            # │  │ │ │ │
            # *  * * * *
    - cron:  '0 20 * * 5'
  workflow_dispatch:
    branches: [ main ]

jobs:
  choose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run chooser
        run: node src/index.js choose

      - name: Get selection description
        id: vars
        run: echo "desc=$(cat ./files/desc.txt)" >> $GITHUB_OUTPUT

      - name: Get selection DOI
        id: vars
        run: echo "doi=$(cat ./files/next.txt)" >> $GITHUB_OUTPUT

      - name: Create commit
        run: |
          git config user.name 'Neea Rusch'
          git config user.email 'nkrusch@users.noreply.github.com'
          git add -A
          git commit -m "Choose next paper"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: files/*.txt
          commit-message: Next paper selection ${{ steps.vars.outputs.doi }}
          body: ${{ steps.vars.outputs.desc }}
          reviewers: nkrusch