name: Vote close

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    branches: [ main ]

jobs:
  close:
    # This workflow runs when:
    # 1. dispatched manually or
    # 2. "paper-vote"-labelled PR was merged to main branch
    if: ${{ github.event_name != 'pull_request' ||
           (github.event.pull_request.merged == true
            && contains(github.event.pull_request.labels.*.name, 'paper-vote')) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        options: [1, 2, 3, 4]
    steps:

      - name: 🕵️ Locate remaining vote option pull requests
        uses: juliangruber/find-pull-request-action@v1
        id: find-pr
        with:
          branch: paper-vote-${{ matrix.options }}

      - name: 🏁 Close pull request ${{ matrix.options }}
        if: ${{ steps.find-pr.outputs.number }}
        run: gh pr close --delete-branch ${{ steps.find-pr.outputs.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}