name: Notifications

on:
  pull_request:
    types:
      - closed

jobs:
  notifications:
    if: ${{ github.event.pull_request.merged == true &&
            contains(github.event.pull_request.labels.*.name, 'next-paper') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get selection details
        id: vars
        run: |
          echo "title=$(sed -n '1p' ./data/desc.txt)" >> $GITHUB_OUTPUT && 
          echo "mla=$(sed -n '2p' ./data/desc.txt)" >> $GITHUB_OUTPUT

      - name: Discord notification
        if: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Next paper: ${{ steps.vars.outputs.title }}\n\n${{ steps.vars.outputs.mla }}"

      - name: Send custom JSON data to Slack workflow
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-message: "Next paper: ${{ steps.vars.outputs.title }}\n\n${{ steps.vars.outputs.mla }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK