name: Set suggestion

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      doi:
        description: DOI, e.g. 10.1122/9991234
        required: true

# This is a mirror of the "choose" workflow, but without randomization.
# The next paper suggestion is set manually from a DOI.
# It generates a pull request and applies website edits.
# The generated PR still needs to be merged by repository maintainer.
jobs:
  set_paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 🎯 Set paper selection
        run: npm run set -- ${{ github.event.inputs.doi }}
      - name: 📝 Update website
        run: npm run web
      - name: ✅ Commit paper selection changes
        run: bash ${PWD}/.github/utils/commit.sh
      - name: 🔎 Lookup paper details
        id: vars
        run: |
          echo "title=$(bash .github/utils/title.sh)" >> $GITHUB_OUTPUT
          echo "body=$(bash .github/utils/pr.sh)" >> $GITHUB_OUTPUT
      - name: 🔖️ Create a pull request
        id: paperpr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: files/*.txt
          labels: next-paper
          branch: next-paper
          title: ${{ steps.vars.outputs.title }}
          body: ${{ steps.vars.outputs.body }}
          delete-branch: true
