name: "Test changes"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Command tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm run choose
      - run: npm run set -- 10.1145/3622831
      - run: npm run web
      - run: npm run stats